version: '3'

networks:
  rsa:
    driver: bridge

services:
  nginx:
    image: nginx:1.17
    container_name: rsa-nginx
    ports:
      - 8085:80
    volumes:
      - .:/code
      - ./docker/nginx/rsa-playground.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rsa

  php:
    build:
      context: ./docker/php
    container_name: rsa-php
    ports:
      - 9000:9000
    volumes:
      - .:/code
    networks:
      - rsa
